src/app/views.py
#region IMPORTS
import pathlib
import os
import logging
import sys
import json
import requests
import uuid
import cv2
import numpy
import base64
from qreader import QReader
from datetime import datetime, timedelta
from hypercorn.logging import AccessLogAtoms
from flask import Blueprint, session, request, render_template, redirect, url_for, flash

from src.app.properties import WebAppPropertiesManager
from src.common.firebase import FirebaseService
#endregion

views = Blueprint("views", __name__)

class CustomFormatter(logging.Formatter):
    def format(self, record):
        if record.args != ():
            if isinstance(record.args, AccessLogAtoms):
                return super().format(record)
            argList = []
            for arg in record.args:
                if arg is None:
                    argList.append('')
                else:
                    argList.append(arg)
            fullMsg = record.msg % (tuple(argList))
        else:
            fullMsg = record.msg
        escapedMsg = fullMsg.replace('\\', '\\\\').replace('"', '\\"')
        record.msg = escapedMsg
        record.args = ()
        return super().format(record)
    
# create log folder if it doesn't exist
if not os.path.exists('Logs'):
    os.mkdir('Logs')

# create log handlers and assign custom formatter
parentDir = str(pathlib.Path(__file__).parent.parent.parent.absolute()).replace("\\",'/')
fileHandler = logging.FileHandler(filename = parentDir + '/Logs/HalloweenEventWebApp.log')
stdoutHandler = logging.StreamHandler(sys.stdout)
customFormatter = CustomFormatter('{"level":"%(levelname)s","time":"%(asctime)s","message":"%(message)s","name":"%(name)s"}')
fileHandler.setFormatter(customFormatter)
stdoutHandler.setFormatter(customFormatter)
handlers = [fileHandler, stdoutHandler]

# initialize logger
logging.basicConfig(handlers = handlers, 
                    level = logging.INFO)
logger = logging.getLogger()

# start property manager and get properties
WebAppPropertiesManager.startPropertyManager()
logger.setLevel(WebAppPropertiesManager.LOG_LEVEL)

# start firebase scheduler
FirebaseService.startFirebaseScheduler(WebAppPropertiesManager.FIREBASE_CONFIG_JSON)

openSessions = dict()
def expireServerSessions():
    currentTime = datetime.now()
    expiredSessionIds = []
    for sessionId, session in openSessions.items():
        createdTime = session["created"]
        if (currentTime - createdTime >= timedelta(days = 1)):
            expiredSessionIds.append(sessionId)
    for sessionId in expiredSessionIds:
        openSessions.pop(sessionId)

def createNewSession(session, userKey, encodedImage, displayName):
    global openSessions
    if not os.path.exists('QR Codes'):
        os.mkdir('QR Codes')
    filename = "src/app/static/" + userKey + ".png"
    with open(filename, 'wb') as f:
        f.write(base64.decodebytes(encodedImage))
    newSessionId = str(uuid.uuid4())
    openSessions[newSessionId] = {"userKey": userKey, "displayName": displayName, "created": datetime.now()}
    session["sessionId"] = newSessionId

def endSession(session):
    global openSessions
    if "sessionId" in session:
        openSessions.pop(session["sessionId"])
        session.pop("sessionId", None)

def sessionExists(session):
    global openSessions
    if "sessionId" not in session:
        return False
    return session["sessionId"] in openSessions

def getSessionUserKey(session):
    global openSessions
    return openSessions[session["sessionId"]]["userKey"]

def getSessionUserName(session):
    global openSessions
    return openSessions[session["sessionId"]]["displayName"]

def getScoreboard():
    # TODO
    try:
        response = requests.get(WebAppPropertiesManager.API_HOST + "/scoreboard/",
                                verify=False)
        return response.json()
    except Exception as e:
        logger.error(e)
        return None

@views.route("/", defaults = {"path": ""})
@views.route("/<path:path>")
def root(path):
    if sessionExists(session):
        return redirect(url_for("views.feed"))
    else:
        return redirect(url_for("views.participate"))

@views.route("/feed/")
def feed():
    if sessionExists(session):
        participateLoginStyle = "style=\"display: none;\""
        logoutFeedProfileStyle = ""
    else:
        return redirect(url_for("views.login"))
    try:
        scoreboardJson = getScoreboard()
        scoreboardHTML = ""
        topScore = 0

        if scoreboardJson != None:
            for event in scoreboardJson["scoreboard"]:
                scoreboardHTML += f'<div class=\"w3-cell-row\"><div class=\"w3-cell w3-container\"><h3>{event["winner"]} defeated {event["loser"]}.</h3><h5>Time: {event["time"]}</h5></div></div><hr>'

            topScore = scoreboardJson["topScore"]

        return render_template("feed.html", participateLoginStyle = participateLoginStyle, logoutFeedProfileStyle = logoutFeedProfileStyle, scoreboard = scoreboardHTML, topScore = topScore)
    except Exception:
        pass;  

    return render_template("feed.html", participateLoginStyle = participateLoginStyle, logoutFeedProfileStyle = logoutFeedProfileStyle, scoreboard = "")

@views.route("/scan/", methods = ["POST"])
def scan():
    if not sessionExists(session):
        return redirect(url_for("views.login"))
    try:
        file = request.files["file"].read()
        nparr = numpy.fromstring(file, numpy.uint8)
        imageNp = cv2.imdecode(nparr, cv2.COLOR_BGR2RGB)
        qreader = QReader()
        decodedText = qreader.detect_and_decode(image = imageNp)
        return (decodedText[0], 200)
    except Exception:
        return ("Error scanning QR code.", 400)

@views.route("/fight/")
def fight():
    if sessionExists(session):
        participateLoginStyle = "style=\"display: none;\""
        logoutFeedProfileStyle = ""
    else:
        return redirect(url_for("views.login"))
    
    args = request.args
    scannedUserKey = args.get('scannedUserKey')
    scannerUserKey = getSessionUserKey(session)

    try:
        fightResponse = requests.post(WebAppPropertiesManager.API_HOST + "/fight/", data = json.dumps({"scannedUserKey": scannedUserKey, "scannerUserKey": scannerUserKey}))
        if fightResponse.status_code >= 400:
            raise Exception
        flash("Fight Complete", 'success')
        fight = fightResponse.json()
        if "winner" in fight and "loser" in fight and "time" in fight and "winnerKey" in fight and "loserKey" in fight:
            fightHTML = f'<div class=\"w3-cell-row\"><div class=\"w3-cell w3-container\"><h3>{fight["winner"]} defeated {fight["loser"]}.</h3><h5>Time: {fight["time"]}</h5></div></div><hr>'

            if fight["winnerKey"] == scannerUserKey and fight["loserKey"] == scannedUserKey:
                fightHTML += f"<div class=\"w3-cell-row\"><div class=\"w3-cell w3-container\"><img class=\"youWon\" src=\"{url_for('static', filename='youWon.png')}\"></div></div><hr>"
                return render_template("youWon.html", participateLoginStyle = participateLoginStyle, logoutFeedProfileStyle = logoutFeedProfileStyle, fightHTML = fightHTML)
            else:
                fightHTML += f"<div class=\"w3-cell-row\"><div class=\"w3-cell w3-container\"><img class=\"youDied\" src=\"{url_for('static', filename='youDied.png')}\"></div></div><hr>"
                return render_template("youLost.html", participateLoginStyle = participateLoginStyle, logoutFeedProfileStyle = logoutFeedProfileStyle, fightHTML = fightHTML)
    except:
        flash(fightResponse.json()["message"], 'error')
        if fightResponse.status_code == 403:
            fightHTML = f"<div class=\"w3-cell-row\"><div class=\"w3-cell w3-container\"><img class=\"niceTry\" src=\"{url_for('static', filename='niceTry.png')}\"></div></div><hr>"
            return render_template("noFight.html", participateLoginStyle = participateLoginStyle, logoutFeedProfileStyle = logoutFeedProfileStyle, fightHTML = fightHTML)

    return redirect(url_for("views.feed"))

@views.route("/qrcode/")
def qrcode():
    if sessionExists(session):
        participateLoginStyle = "style=\"display: none;\""
        logoutFeedProfileStyle = ""
    else:
        return redirect(url_for("views.login"))

    qrcodeHTML = f"<div class=\"w3-cell-row\"><div class=\"w3-cell w3-container\"><img class=\"qrcode\" src=\"{url_for('static', filename=getSessionUserKey(session) + '.png')}\"></div></div><hr>"
    return render_template("qrcode.html", participateLoginStyle = participateLoginStyle, logoutFeedProfileStyle = logoutFeedProfileStyle, qrcodeHTML = qrcodeHTML)

@views.route("/profile/", methods = ["GET", "POST"])
def profile():
    if sessionExists(session):
        participateLoginStyle = "style=\"display: none;\""
        logoutFeedProfileStyle = ""
    else:
        return redirect(url_for("views.login"))
    if request.method == "POST":
        email = request.form['email']
        password = request.form['password']

        try:
            updateProfileResponse = requests.put(WebAppPropertiesManager.API_HOST + "/users/", data = json.dumps({"userKey": getSessionUserKey(session), "email": email, "password": password}))
            password = None
            if updateProfileResponse.status_code == 400:
                raise Exception
            flash("Profile Updated", 'success')
        except:
            password = None
            flash(updateProfileResponse.json()["message"], 'error')
        return redirect(url_for("views.profile"))

    return render_template("profile.html", participateLoginStyle = participateLoginStyle, logoutFeedProfileStyle = logoutFeedProfileStyle, displayName = getSessionUserName(session))

@views.route("/logout/")
def logout():
    if sessionExists(session):
        endSession(session)
        return redirect(url_for("views.login"))
    return ('', 204)

@views.route("/participate/", methods = ["GET", "POST"])
def participate():
    if sessionExists(session):
        return redirect(url_for("views.feed"))

src/app/templates/feed.html
{% extends "index.html" %}
{% block content %}
<div class="scoreboard">
    <div class="w3-container events">
        <hr>
        <div class="w3-cell-top-score">
            <div class="w3-cell w3-container">
                <h3 class="w3-cell-top-score-text">Top Score: <span class="topScore">{{topScore}}</span></h3>
            </div>
        </div>
        <hr>
        {{scoreboard|safe}}
    </div>
</div>
{% endblock %}

src/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>The Long Night</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3pro.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-orange.css">
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
    {{ toastr.include_jquery() }}
    {{ toastr.include_toastr_css() }}
    {{ toastr.message() }}
</head>
<div class="loader" id="loaderElement"></div>
<body>
    <nav class="w3-sidebar w3-bar-block w3-card" id="mySidebar">
        <div class="w3-container w3-theme-d2">
          <span onclick="closeSidebar()" class="w3-button w3-display-topright w3-large">X</span>
          <br>
          <div class="w3-padding w3-center">
            <img class="w3-circle" src="{{url_for('static', filename='logo.png')}}" alt="avatar">
          </div>
        </div>
        <a class="w3-bar-item w3-button nav-button-text custom-hover" {{participateLoginStyle|safe}} href="{{url_for('views.participate')}}">Participate</a>
        <a class="w3-bar-item w3-button nav-button-text custom-hover" {{participateLoginStyle|safe}} href="{{url_for('views.login')}}">Login</a>
        <a class="w3-bar-item w3-button nav-button-text custom-hover" {{logoutFeedProfileStyle|safe}} href="{{url_for('views.feed')}}">Feed</a>
        <a class="w3-bar-item w3-button nav-button-text custom-hover" {{logoutFeedProfileStyle|safe}} onclick="openCamera()">Scan</a>
        <a class="w3-bar-item w3-button nav-button-text custom-hover" {{logoutFeedProfileStyle|safe}} href="{{url_for('views.qrcode')}}">QR Code</a>
        <a class="w3-bar-item w3-button nav-button-text custom-hover" {{logoutFeedProfileStyle|safe}} href="{{url_for('views.profile')}}">Profile</a>
        <a class="w3-bar-item w3-button nav-button-text custom-hover" {{logoutFeedProfileStyle|safe}} href="{{url_for('views.logout')}}">Logout</a>
        <input id="cameraFileInput" type="file" accept="image/*" capture="environment" scanURL="{{url_for('views.scan')}}" onclick="this.value=null;"/>
    </nav>
    <header class="w3-bar w3-card w3-theme header">
        <button class="w3-bar-item w3-button w3-xlarge w3-hover-theme hamburger-button" onclick="openSidebar()">&#9776;</button>
        <div class="w3-bar-item website-title">
            <h1 class="header-text-top">The Long Night</h1>
            <h2 class="header-text-bottom">A StormerG Halloween Game</h3>
        </div>
    </header>
    {% block content %}
    {% endblock %}
    <div class="footer-placeholder"></div>
    <footer class="w3-container w3-theme footer">
        <h1 class="footer-text">Happy Halloween</h3>
    </footer>
    {{ toastr.include_toastr_js() }}
</body>
<script type="text/javascript" src="{{url_for('static', filename='index.js')}}"></script>
</html>

src/app/templates/login.html
{% extends "index.html" %}
{% block content %}
<div class="login" >
    <h3 class="welcome">Welcome to The Long Night!</h3>
    <div class="log-back-in">
        <p>Did you already sign up to participate?<br>Log back in below!<p>
    </div>
    <div class="forms">
        <form action = "{{url_for('views.login')}}" method = "post">
            <p><input class="input" type=email name=email required=true placeholder="Email"></p>
            <p><input class="input" type=password name=password required=true placeholder="Password"></p>
            <p><input class="button" type=submit value="Log In"></p>
        </form>
     </div>
</div>
{% endblock %}

src/app/templates/noFight.html
{% extends "index.html" %}
{% block content %}
<div class="no-fight">
    <div class="w3-container events">
        <hr>
        {{fightHTML|safe}}
    </div>
</div>
{% endblock %}

src/app/templates/participate.html
{% extends "index.html" %}
{% block content %}
<div class="participate" >
    <h3 class="welcome">Welcome to The Long Night!</h3>
    <div class="instructions">
        <ol>
            <li>You will receive your own QR code.</li>
            <li>Scan as many other players' QR codes to fight them once.</li>
            <li>The random winner of a fight will get 2 points and the loser will get 1 point.</li>
            <li>The player with the most points at the end of The Long Night by {{shutdownTime}} wins.</li>
            <li>You will also be sent a summary at the end of The Long Night of who you interacted with!</li>
            <li>Sign up below to participate!</li>
        </ol>
    </div>
    <div class="forms">
        <form action = "{{url_for('views.participate')}}" method = "post">
            <p><input class="input" type=text name=name required=true placeholder="Display Name"></p>
            <p><input class="input" type=email name=email required=true placeholder="Email"></p>
            <p><input class="input" type=password name=password required=true placeholder="Password"></p>
            <p><input class="button" type = submit value = "Sign Up"></p>
        </form>
     </div>
</div>
{% endblock %}

src/app/templates/profile.html
{% extends "index.html" %}
{% block content %}
<div class="profile" >
    <h3 class="welcome">Signed in as {{displayName}}</h3>
    <div class="log-back-in">
        <p>Need to change your email or password?<br>Update them below!<p>
    </div>
    <div class="forms">
        <form action = "{{url_for('views.profile')}}" method = "post">
            <p><input class="input" type = email name = email placeholder="Email"></p>
            <p><input class="input" type = password name = password placeholder="Password"></p>
            <p><input class="button" type = submit value = "Save"></p>
        </form>
     </div>
</div>
{% endblock %}

src/app/templates/qrcode.html
{% extends "index.html" %}
{% block content %}
<div class="qrcode-placeholder">
    <div class="w3-container events">
        <hr>
        {{qrcodeHTML|safe}}
    </div>
</div>
{% endblock %}

src/app/templates/youLost.html
{% extends "index.html" %}
{% block content %}
<div class="you-lost">
    <div class="w3-container events">
        <hr>
        {{fightHTML|safe}}
    </div>
</div>
{% endblock %}

src/app/templates/youWon.html
{% extends "index.html" %}
{% block content %}
<div class="you-won">
    <div class="w3-container events">
        <hr>
        {{fightHTML|safe}}
    </div>
</div>
{% endblock %}